---
title: "Results MBON_CORALNET"
author: "Gonzalo Bravo"
date: "9/8/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, code=readLines("READ_DATA.R"), include=FALSE}
library(ggplot2)
```


# FUNCTIONAL GROUPS RESULTS
```{r plot1, echo=FALSE,fig.height = 10, fig.width = 10, fig.align = "center"}
ggplot(Coverdata.FG,aes(x=strata,y=cover.rel.mean,fill=Comments)) + geom_bar(alpha=0.7,stat="identity",color="black",position=position_dodge()) + scale_color_grey() + geom_errorbar(aes(ymin=cover.rel.mean-cover.rel.SE, ymax=cover.rel.mean+cover.rel.SE), width=.2,position=position_dodge(.9)) + theme_bw() + scale_y_continuous(limits = c(0,100))+ scale_x_discrete(limits=c("HIGHTIDE","MIDTIDE","LOWTIDE"),labels=c("HIGH","MID","LOW")) + facet_grid(country~CATAMI) + labs(fill = "Method",x = "", y = "Cover (%)", title = "",caption ="Mean + SE") + theme(legend.position = "bottom",panel.grid.major = element_blank(),panel.grid.minor = element_blank(),panel.background = element_blank()) + scale_fill_brewer(palette="Dark2")
```

\pagebreak

## CATAMI list
```{r CATAMIlistdefinition, echo=FALSE, message=FALSE, warning=FALSE}
knitr::kable(labelset)
```


```{r plot4, echo=FALSE, fig.height = 10, fig.width = 10, fig.align = "center"}
ggplot(Coverdata_abundant,aes(x=strata,y=cover.rel.mean,fill=Comments)) + geom_bar(alpha=0.7,stat="identity",color="black",position=position_dodge()) + scale_color_grey() + geom_errorbar(aes(ymin=cover.rel.mean-cover.rel.SE, ymax=cover.rel.mean+cover.rel.SE), width=.2,position=position_dodge(.9)) + theme_bw() + scale_y_continuous(limits = c(0,100))+ scale_x_discrete(limits=c("HIGHTIDE","MIDTIDE","LOWTIDE"),labels=c("HIGH","MID","LOW")) + facet_grid(country~CATAMI) + labs(fill = "Method",x = "", y = "Cover (%)", title = "",caption ="Mean + SE") + theme(legend.position = "bottom",panel.grid.major = element_blank(),panel.grid.minor = element_blank(),panel.background = element_blank())  + scale_fill_brewer(palette="Dark2")
```

\pagebreak

## BOXPLOT
```{r plot5, echo=FALSE,fig.height = 10, fig.width = 10, fig.align = "center"}
ggplot(data=PQ_VQ_long.FG, mapping=aes(x=strata, y=cover,fill=Comments)) +geom_boxplot()   + theme_bw() + scale_y_continuous(limits = c(0,100))+ scale_x_discrete(limits=c("HIGHTIDE","MIDTIDE","LOWTIDE"),labels=c("HIGH","MID","LOW")) + facet_grid(country~CATAMI) + labs(fill = "Method",x = "", y = "Cover (%)", title = "") + theme(legend.position = "bottom",panel.grid.major = element_blank(),panel.grid.minor = element_blank(),panel.background = element_blank())  + scale_fill_brewer(palette="Dark2")
```

\pagebreak
## Method comparison

```{r correlations, include=FALSE}
library(ggpubr) 
```

```{r correlations2, include=FALSE}
library(gridExtra)
library(gridGraphics)
library(cowplot)
#SUBSTRATE------
#by site
SC<-  FG
#differenced_data= Method_A - Method_B
SC$diff <- SC$SUBSTRATE.R-SC$SUBSTRATE.H
SC$avg <- SC$SUBSTRATE.H


#by country
SC2 <- SC %>% 
  group_by(country) %>% 
  summarise_at(vars(SUBSTRATE.R,SUBSTRATE.H,diff,avg), 
               list(mean, sd)) 
colnames(SC2) <- c("country","SUBSTRATE.R.mean","SUBSTRATE.H.mean","diff","avg","SUBSTRATE.R.SD","SUBSTRATE.H.SD","diff.SD","avg.SD")


#plot by photo
g1 <- ggplot(SC, aes(x=avg, y=diff,colour=country,shape=strata))+geom_hline(yintercept=0) + geom_point()+ theme_bw()+labs(y="Difference in % cover between methods", x="",title = "Substrate")+theme(legend.position="none",plot.margin=unit(c(0,0,1,1), "cm"))
#plot by site
g2 <- ggplot(SC2, aes(x=avg, y=diff,colour=country)) + geom_point()+theme_bw() + labs(y="", x="Avg % cover by VQ.Human (± SD)") + theme(axis.title.y =element_blank(),axis.text.y=element_blank(),axis.ticks.y=element_blank())+geom_hline(yintercept=0)+theme(legend.position="none",plot.margin=unit(c(0,1,1,-0.1), "cm"))+geom_errorbar(aes(ymin =diff-diff.SD,ymax =diff+diff.SD),width = 0.2) + geom_errorbarh(aes(xmin =avg-avg.SD ,xmax = avg+avg.SD),height =-.2)

#set y limits and brecks
limits <- c(-30, 30)#see plot to set 
breaks <- seq(limits[1], limits[2], by=8)

# assign common axis to both plots
p1.common.y <- g1 + scale_y_continuous(limits=limits, breaks=breaks)
p2.common.y <- g2 + scale_y_continuous(limits=limits, breaks=breaks)

# At this point, they have the same axis, but the axis lengths are unequal, so ...
# build the plots 
p1.common.y <- ggplot_gtable(ggplot_build(p1.common.y))
p2.common.y <- ggplot_gtable(ggplot_build(p2.common.y))

# copy the plot height from p1 to p2
p2.common.y$heights <- p1.common.y$heights
#plot grid
grid <- grid.arrange(p1.common.y,p2.common.y,ncol=2,widths=c(1,1))

#add legend
legend <- ggplot(SC, aes(x=avg, y=diff,colour=country,shape=strata))+geom_hline(yintercept=0) + geom_point()+ theme_bw()+labs(y="Difference in % cover between methods", x="",title = "Substrate")+theme(legend.position="bottom",legend.title = element_blank(),legend.box="vertical",plot.margin=unit(c(0,0,1,1), "cm"))
legend_plot <- get_legend(legend)#take legend
plot.SUBSTRATE <- plot_grid(legend_plot,grid, ncol = 1, rel_heights = c(.25,1))



#ALGAE------
#by site
AL<-  FG
#differenced_data= Method_A - Method_B
AL$diff <- AL$ALGAE.R-AL$ALGAE.H
AL$avg <- AL$ALGAE.H


#by country
AL2 <- AL %>% 
  group_by(country) %>% 
  summarise_at(vars(ALGAE.R,ALGAE.H,diff,avg), 
               list(mean, sd)) 
colnames(AL2) <- c("country","ALGAE.R.mean","ALGAE.H.mean","diff","avg","ALGAE.R.SD","ALGAE.H.SD","diff.SD","avg.SD")


#plot by photo
P.AL1 <- ggplot(AL, aes(x=avg, y=diff,colour=country,shape=strata))+geom_hline(yintercept=0) + geom_point()+ theme_bw()+labs(y="Difference in % cover between methods", x="",title = "ALGAE")+theme(legend.position="none",plot.margin=unit(c(0,0,1,1), "cm"))
#plot by site
P.AL2 <- ggplot(AL2, aes(x=avg, y=diff,colour=country)) + geom_point()+theme_bw() + labs(y="", x="Avg % cover by VQ.Human (± SD)") + theme(axis.title.y =element_blank(),axis.text.y=element_blank(),axis.ticks.y=element_blank())+geom_hline(yintercept=0)+theme(legend.position="none",plot.margin=unit(c(0,1,1,-0.1), "cm"))+geom_errorbar(aes(ymin =diff-diff.SD,ymax =diff+diff.SD),width = 0.2) + geom_errorbarh(aes(xmin =avg-avg.SD ,xmax = avg+avg.SD),height =-.2)

#set y limits and brecks
limits <- c(-30, 30)#see plot to set 
breaks <- seq(limits[1], limits[2], by=8)

# assign common axis to both plots
p1.common.y <- P.AL1 + scale_y_continuous(limits=limits, breaks=breaks)
p2.common.y <- P.AL2 + scale_y_continuous(limits=limits, breaks=breaks)

# At this point, they have the same axis, but the axis lengths are unequal, so ...
# build the plots 
p1.common.y <- ggplot_gtable(ggplot_build(p1.common.y))
p2.common.y <- ggplot_gtable(ggplot_build(p2.common.y))

# copy the plot height from p1 to p2
p2.common.y$heights <- p1.common.y$heights
#plot grid
grid <- grid.arrange(p1.common.y,p2.common.y,ncol=2,widths=c(1,1))

#add legend
legend <- ggplot(AL, aes(x=avg, y=diff,colour=country,shape=strata))+geom_hline(yintercept=0) + geom_point()+theme(legend.position="bottom",legend.title = element_blank(),legend.box="vertical",plot.margin=unit(c(0,0,1,1), "cm"))
legend_plot <- get_legend(legend)#take legend
plot.ALGAE <- plot_grid(legend_plot,grid, ncol = 1, rel_heights = c(.25,1))





#INVERTEBRATES------
#by site
IN<-  FG
#differenced_data= Method_A - Method_B
IN$diff <- IN$INVERTEBRATES.R-IN$INVERTEBRATES.H
IN$avg <- IN$INVERTEBRATES.H


#by country
IN2 <- IN %>% 
  group_by(country) %>% 
  summarise_at(vars(INVERTEBRATES.R,INVERTEBRATES.H,diff,avg), 
               list(mean, sd)) 
colnames(IN2) <- c("country","INVERTEBRATES.R.mean","INVERTEBRATES.H.mean","diff","avg","INVERTEBRATES.R.SD","INVERTEBRATES.H.SD","diff.SD","avg.SD")


#plot by photo
P.IN1 <- ggplot(IN, aes(x=avg, y=diff,colour=country,shape=strata))+geom_hline(yintercept=0) + geom_point()+ theme_bw()+labs(y="Difference in % cover between methods", x="",title = "INVERTEBRATES")+theme(legend.position="none",plot.margin=unit(c(0,0,1,1), "cm"))
#plot by site
P.IN2 <- ggplot(IN2, aes(x=avg, y=diff,colour=country)) + geom_point()+theme_bw() + labs(y="", x="Avg % cover by VQ.Human (± SD)") + theme(axis.title.y =element_blank(),axis.text.y=element_blank(),axis.ticks.y=element_blank())+geom_hline(yintercept=0)+theme(legend.position="none",plot.margin=unit(c(0,1,1,-0.1), "cm"))+geom_errorbar(aes(ymin =diff-diff.SD,ymax =diff+diff.SD),width = 0.2) + geom_errorbarh(aes(xmin =avg-avg.SD ,xmax = avg+avg.SD),height =-.2)

#set y limits and brecks
limits <- c(-30, 30)#see plot to set 
breaks <- seq(limits[1], limits[2], by=8)

# assign common axis to both plots
p1.common.y <- P.IN1 + scale_y_continuous(limits=limits, breaks=breaks)
p2.common.y <- P.IN2 + scale_y_continuous(limits=limits, breaks=breaks)

# At this point, they have the same axis, but the axis lengths are unequal, so ...
# build the plots 
p1.common.y <- ggplot_gtable(ggplot_build(p1.common.y))
p2.common.y <- ggplot_gtable(ggplot_build(p2.common.y))

# copy the plot height from p1 to p2
p2.common.y$heights <- p1.common.y$heights
#plot grid
grid <- grid.arrange(p1.common.y,p2.common.y,ncol=2,widths=c(1,1))

#add legend
legend <- ggplot(IN, aes(x=avg, y=diff,colour=country,shape=strata))+geom_hline(yintercept=0) + geom_point()+ theme_bw()+labs(y="Difference in % cover between methods", x="",title = "INVERTEBRATES")+theme(legend.position="bottom",legend.title = element_blank(),legend.box="vertical",plot.margin=unit(c(0,0,1,1), "cm"))
legend_plot <- get_legend(legend)#take legend
plot.INVERTEBRATES <- plot_grid(legend_plot,grid, ncol = 1, rel_heights = c(.25,1))


```

```{r plot12, echo=FALSE, message=FALSE, warning=FALSE,fig.height = 6, fig.width = 6}
plot.INVERTEBRATES
```

```{r plot13, echo=FALSE, message=FALSE, warning=FALSE,fig.height = 5, fig.width = 6}
plot.ALGAE
```


```{r plot14, echo=FALSE, message=FALSE, warning=FALSE,fig.height = 5, fig.width = 6}
plot.SUBSTRATE
```
\pagebreak

See plots explanation in :
Vallès H, Oxenford HA, Henderson A (2019) Switching between standard coral reef benthic monitoring protocols is complicated: proof of concept. PeerJ 7:e8167


# Code and data files 
All the codes and data files are in github

https://github.com/gonzalobravoargentina/CoralNet_MBON
